commands:
  # Hora
  - command:
    input:  Me diga as horas.
    entity: time
    action: getTime
  - command:
    input:  Que horas são.
    entity: time
    action: getTime
  - command:
    input:  Eu quero saber as horas.
    entity: time
    action: getTime  
  # data
  - command:
    input:  Qual é a data de hoje?
    entity: time
    action: getDate 
  - command:
    input:  Data de hoje?
    entity: time
    action: getDate  
  # Tempo
  - command:
    input: Previsão do tempo.
    entity: weather
    action: getWeather
  - command:
    input: Como está o clima?
    entity: weather
    action: getWeather  
  #Open
  - command:
    input: Abrir google
    entity: open
    action:
  - command:
    input: Abra o youtube
    entity: open
    action: